#!/bin/bash

init() {
  set -e

  version=$(./utils/assert requiredArg first "version" $1)
  platform=$(./utils/assert requiredArg second "platform (linux or mac)" $2)
  arch=$(./utils/assert requiredArg third "arch (amd64 or arm64)" $3)

  source ./utils/globals

  zellij_platform=$(./utils/env select_platform $platform unknown-linux-musl apple-darwin)
  zellij_arch=$(./utils/env select_arch $arch x86_64 aarch64)
  zellij_filename=zellij-no-web-${zellij_arch}-${zellij_platform}
  zellij_file=$zellij_filename.tar.gz
  zellij_url=https://github.com/zellij-org/zellij/releases/download/v$version/$zellij_file
  zellij_bin=$(./utils/bin find zellij)

  # initializing directories
  downloads_folder=$ds_downloads_folder
  tools_folder=$ds_tools_folder
  bin_folder=$ds_bin_folder

  ./utils/assert notEmpty "Downloads folder variable is required" $downloads_folder
  ./utils/assert notEmpty "Tools folder variable is required" $tools_folder
  ./utils/assert notEmpty "Bin folder variable is required" $bin_folder

  mkdir -p $downloads_folder
  mkdir -p $tools_folder
  mkdir -p $bin_folder
}

run() {
  echo "Checking ZelliJ installation..."

  init $@

  check_installation

  echo ""
}

sync() {
  echo "Syncing ZelliJ binaries..."

  init $@

  create_symlinks

  echo ""
}

check_installation() {
  if [ "$zellij_bin" = "" ]; then
    echo "ZelliJ is not installed, installing..."
    install
  else
    current_version=$(zellij --version | sed "s|zellij ||")
    echo "ZelliJ is already installed. [current=$current_version; target=$version]"
    if [ "$version" != "$current_version" ]; then
      echo "ZelliJ version mismatch, replacing installation..."
      rm -rf $tools_folder/zellij
      install
    fi
  fi
}

install() {
  rm -Rf $downloads_folder/$zellij_file
  echo "Downloading ZelliJ from $zellij_url"
  curl -L --output $downloads_folder/$zellij_file $zellij_url

  mkdir -p $tools_folder/zellij
  tar -xzf $downloads_folder/$zellij_file -C $tools_folder/zellij

  create_symlinks

  rm -Rf $downloads_folder/$zellij_file
}

create_symlinks() {
  ./utils/symlink create "$tools_folder/zellij/zellij" "$bin_folder/zellij"
}

"$@"
